# -*- coding: utf-8 -*-
"""ner_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhApXe8eoObEuxrRld-WsOgKRowHkyfi
"""

!pip install streamlit transformers torch

!pip install spacy
!python -m spacy download en_core_web_sm

from transformers import pipeline

# Load pre-trained NER model and tokenizer
ner_model = pipeline("ner", grouped_entities=True)

# Function to extract named entities
def perform_ner(text):
    return ner_model(text)

import spacy

# Load the spaCy NER model
nlp = spacy.load("en_core_web_sm")

# Function to extract named entities
def perform_ner(text):
    doc = nlp(text)
    return [(ent.text, ent.label_) for ent in doc.ents]

import streamlit as st
from transformers import pipeline

# Load pre-trained NER model and tokenizer
ner_model = pipeline("ner", grouped_entities=True)

# Title of the app
st.title("Named Entity Recognition (NER) App")

# Text input
user_input = st.text_area("Enter the text for NER analysis", "Type your text here...")

# If user inputs text, perform NER
if st.button("Analyze"):
    if user_input:
        # Perform NER on the user's input
        ner_results = ner_model(user_input)

        # Display the results
        st.subheader("Named Entities:")
        for entity in ner_results:
            st.write(f"**Entity:** {entity['word']} | **Label:** {entity['entity_group']} | **Score:** {entity['score']:.2f}")
    else:
        st.warning("Please enter some text to analyze.")